"""Initial migration

Revision ID: b9edd739e75c
Revises: 
Create Date: 2025-11-27 20:09:16.058878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9edd739e75c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('kits')
    # op.drop_table('usuario_empresas')
    # op.alter_column('almacenes', 'es_principal',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True,
    #            existing_server_default=sa.text('0'))
    op.add_column('equipos', sa.Column('codigo_unico', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'equipos', ['codigo_unico'])
    # op.drop_constraint(None, 'kit_componentes', type_='foreignkey')
    # op.create_foreign_key(None, 'kit_componentes', 'tipos_equipo', ['tipo_equipo_id'], ['id'])
    # op.drop_column('producto_fotos', 'ruta_archivo')
    # op.drop_column('producto_fotos', 'es_principal')
    # op.drop_column('producto_fotos', 'orden')
    # op.drop_column('producto_fotos', 'fecha_registro')
    # op.alter_column('tipos_equipo', 'nombre',
    #            existing_type=sa.VARCHAR(length=100),
    #            type_=sa.String(length=200),
    #            existing_nullable=False)
    # op.drop_column('usuarios', 'rol')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('rol', sa.VARCHAR(length=13), nullable=True))
    op.alter_column('tipos_equipo', 'nombre',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('producto_fotos', sa.Column('fecha_registro', sa.DATETIME(), nullable=True))
    op.add_column('producto_fotos', sa.Column('orden', sa.INTEGER(), nullable=True))
    op.add_column('producto_fotos', sa.Column('es_principal', sa.BOOLEAN(), nullable=True))
    op.add_column('producto_fotos', sa.Column('ruta_archivo', sa.VARCHAR(length=500), nullable=False))
    op.drop_constraint(None, 'kit_componentes', type_='foreignkey')
    op.create_foreign_key(None, 'kit_componentes', 'kits', ['tipo_equipo_id'], ['id'])
    op.drop_constraint(None, 'equipos', type_='unique')
    op.drop_column('equipos', 'codigo_unico')
    op.alter_column('almacenes', 'es_principal',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_table('usuario_empresas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), nullable=False),
    sa.Column('puede_registrar', sa.BOOLEAN(), nullable=True),
    sa.Column('puede_modificar', sa.BOOLEAN(), nullable=True),
    sa.Column('puede_eliminar', sa.BOOLEAN(), nullable=True),
    sa.Column('puede_ver_reportes', sa.BOOLEAN(), nullable=True),
    sa.Column('fecha_asignacion', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kits',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=200), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('activo', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###
